const Users = [
  {
    id: 1,
    first_name: "Nealon",
    last_name: "Wixon",
    email: "nwixon0@oracle.com",
    gender: "Male",
    age: 6,
  },
  {
    id: 2,
    first_name: "Reinold",
    last_name: "Leaver",
    email: "rleaver1@surveymonkey.com",
    gender: "Male",
    age: 4,
  },
  {
    id: 3,
    first_name: "Law",
    last_name: "Cheake",
    email: "lcheake2@telegraph.co.uk",
    gender: "Male",
    age: 50,
  },
  {
    id: 4,
    first_name: "Stanford",
    last_name: "Linggood",
    email: "slinggood3@abc.net.au",
    gender: "Male",
    age: 36,
  },
  {
    id: 5,
    first_name: "Aundrea",
    last_name: "Seeds",
    email: "aseeds4@webs.com",
    gender: "Female",
    age: 50,
  },
  {
    id: 6,
    first_name: "Dallon",
    last_name: "Scrivenor",
    email: "dscrivenor5@dailymail.co.uk",
    gender: "Male",
    age: 33,
  },
  {
    id: 7,
    first_name: "Herrick",
    last_name: "Smyth",
    email: "hsmyth6@chicagotribune.com",
    gender: "Male",
    age: 9,
  },
  {
    id: 8,
    first_name: "Elga",
    last_name: "Hache",
    email: "ehache7@yahoo.com",
    gender: "Female",
    age: 35,
  },
  {
    id: 9,
    first_name: "Lindon",
    last_name: "Wybron",
    email: "lwybron8@msn.com",
    gender: "Male",
    age: 11,
  },
  {
    id: 10,
    first_name: "Aleen",
    last_name: "Josef",
    email: "ajosef9@mashable.com",
    gender: "Female",
    age: 16,
  },
  {
    id: 11,
    first_name: "Wendell",
    last_name: "Birth",
    email: "wbirtha@biblegateway.com",
    gender: "Male",
    age: 51,
  },
  {
    id: 12,
    first_name: "Susannah",
    last_name: "Hanscom",
    email: "shanscomb@tinypic.com",
    gender: "Female",
    age: 82,
  },
  {
    id: 13,
    first_name: "Aurilia",
    last_name: "Diess",
    email: "adiessc@aol.com",
    gender: "Female",
    age: 64,
  },
  {
    id: 14,
    first_name: "Hildegaard",
    last_name: "Daintry",
    email: "hdaintryd@hp.com",
    gender: "Female",
    age: 1,
  },
  {
    id: 15,
    first_name: "Ragnar",
    last_name: "Slate",
    email: "rslatee@ifeng.com",
    gender: "Male",
    age: 40,
  },
  {
    id: 16,
    first_name: "Zelda",
    last_name: "Penhalurick",
    email: "zpenhalurickf@free.fr",
    gender: "Female",
    age: 37,
  },
  {
    id: 17,
    first_name: "Ashia",
    last_name: "Jentin",
    email: "ajenting@usda.gov",
    gender: "Female",
    age: 13,
  },
  {
    id: 18,
    first_name: "Dania",
    last_name: "Jon",
    email: "djonh@webmd.com",
    gender: "Female",
    age: 83,
  },
  {
    id: 19,
    first_name: "Clovis",
    last_name: "Squibbs",
    email: "csquibbsi@adobe.com",
    gender: "Female",
    age: 11,
  },
  {
    id: 20,
    first_name: "Farica",
    last_name: "Piff",
    email: "fpiffj@printfriendly.com",
    gender: "Female",
    age: 40,
  },
  {
    id: 21,
    first_name: "Des",
    last_name: "Brimham",
    email: "dbrimhamk@gmpg.org",
    gender: "Male",
    age: 85,
  },
  {
    id: 22,
    first_name: "Shawn",
    last_name: "Frankiewicz",
    email: "sfrankiewiczl@artisteer.com",
    gender: "Male",
    age: 42,
  },
  {
    id: 23,
    first_name: "Don",
    last_name: "Stack",
    email: "dstackm@dailymotion.com",
    gender: "Male",
    age: 39,
  },
  {
    id: 24,
    first_name: "Werner",
    last_name: "Marden",
    email: "wmardenn@auda.org.au",
    gender: "Male",
    age: 28,
  },
  {
    id: 25,
    first_name: "Kristian",
    last_name: "Jonsson",
    email: "kjonssono@sciencedirect.com",
    gender: "Male",
    age: 78,
  },
  {
    id: 26,
    first_name: "Lloyd",
    last_name: "Toffler",
    email: "ltofflerp@devhub.com",
    gender: "Male",
    age: 61,
  },
  {
    id: 27,
    first_name: "Percy",
    last_name: "Goodyear",
    email: "pgoodyearq@census.gov",
    gender: "Male",
    age: 36,
  },
  {
    id: 28,
    first_name: "Kelli",
    last_name: "Lagden",
    email: "klagdenr@themeforest.net",
    gender: "Female",
    age: 28,
  },
  {
    id: 29,
    first_name: "Dav",
    last_name: "Haggis",
    email: "dhaggiss@seesaa.net",
    gender: "Male",
    age: 25,
  },
  {
    id: 30,
    first_name: "Carolin",
    last_name: "Shemming",
    email: "cshemmingt@answers.com",
    gender: "Female",
    age: 27,
  },
];
export default Users;
